[BITESIZE-14519] Refactor Transformer, fix compilation error
The previous version of the Transformer gave the following
compilation error when `mix compile` was run:

    warning: this clause for call/2 cannot match because a previous clause at line 20 always matches
      lib/belfrage/transformers/bitesize_levels_discriminator.ex:24

We remove the unrequired call/2 clause and refactor the Transformer
to only require one call/2 clause.