implemented a workaround for pesky erlang atom bug
As it turns out Erlang only supports atoms up to length 255.
So it you try to turn a string of length 256 or greater you will get a
compilation error, something like this:

```
Function: 'test ContainerEnvelopeWinnerFlash /container/envelope/winner-flash/*any against live bruce-belfrage /container/envelope/winner-flash/assetUri/%2Fnews%2Felection%2F2021%2Fscotland%2Fconstituencies%2FS16000084/hasFetcher/true?static=true&mode=testData'/1

== Compilation error in file test/smoke/smoke_test.ex ==
** (SystemLimitError) a system limit has been reached
    :erlang.list_to_atom('-test ContainerEnvelopeWinnerFlash /container/envelope/winner-flash/*any against live bruce-belfrage /container/envelope/winner-flash/assetUri/%2Fnews%2Felection%2F2021%2Fscotland%2Fconstituencies%2FS16000084/hasFetcher/true?static=true&mode=testData/1-fun-0-')
    (compiler 8.1.1) v3_core.erl:2058: :v3_core.new_fun_name/1
    ....
    (stdlib 3.17.2) lists.erl:1267: :lists.foldl/3
    (compiler 8.1.1) v3_core.erl:184: :v3_core.module/2
```

Exunit works by turning the describe and test block descriptions into functions
dynamically. This means that the length of the describe + test description must
be less than 255. The decribe + test block together else exunit will error.

When you are creating anonymous functions the compiler names them based upon
the function they're in.

I tried to make an anonymous function within the test block in
`belfrage_smoke_test_case.ex` but in doing do caused the above compiler error.

The solution was to shorten the test description while still making sure the
test name is unique.

I did that by truncating request path, if it was over 100 characters.